language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

install:
    - composer install --no-interaction --no-progress --no-suggest

before_script:
    - ./bin/install-wp-dev

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs

